package com.gaugustini.mhfudatabase.util

import com.gaugustini.mhfudatabase.R
import com.gaugustini.mhfudatabase.data.enums.ArmorType
import com.gaugustini.mhfudatabase.data.enums.ElementType
import com.gaugustini.mhfudatabase.data.enums.ItemIconType
import com.gaugustini.mhfudatabase.data.enums.StatusType
import com.gaugustini.mhfudatabase.data.enums.WeaponType

object MHFUIcons {

    val elements: Map<ElementType, Int> = mapOf(
        ElementType.FIRE to R.drawable.ic_element_fire,
        ElementType.WATER to R.drawable.ic_element_water,
        ElementType.THUNDER to R.drawable.ic_element_thunder,
        ElementType.ICE to R.drawable.ic_element_ice,
        ElementType.DRAGON to R.drawable.ic_element_dragon,
        ElementType.POISON to R.drawable.ic_status_poison,
        ElementType.PARALYSIS to R.drawable.ic_status_paralysis,
        ElementType.SLEEP to R.drawable.ic_status_sleep,
    )

    val status: Map<StatusType, Int> = mapOf(
        StatusType.KNOCKOUT to R.drawable.ic_status_stun,
        StatusType.PARALYSIS to R.drawable.ic_status_paralysis,
        StatusType.POISON to R.drawable.ic_status_poison,
        StatusType.SLEEP to R.drawable.ic_status_sleep,
    )

    val armors: Map<ArmorType, Int> = mapOf(
        ArmorType.HEAD to R.drawable.ic_armor_head,
        ArmorType.CHEST to R.drawable.ic_armor_chest,
        ArmorType.ARMS to R.drawable.ic_armor_arms,
        ArmorType.WAIST to R.drawable.ic_armor_waist,
        ArmorType.LEGS to R.drawable.ic_armor_legs
    )

    val items: Map<ItemIconType, Int> = mapOf(
        ItemIconType.ARMOR_STONE to R.drawable.ic_item_armor_stone,
        ItemIconType.BAG to R.drawable.ic_item_bag,
        ItemIconType.BAIT to R.drawable.ic_item_bait,
        ItemIconType.BALL to R.drawable.ic_item_ball,
        ItemIconType.BARREL to R.drawable.ic_item_barrel,
        ItemIconType.BBQ_SPLIT to R.drawable.ic_item_bbq_split,
        ItemIconType.BINOCULARS to R.drawable.ic_item_binoculars,
        ItemIconType.BOMB to R.drawable.ic_item_bomb,
        ItemIconType.BONE to R.drawable.ic_item_bone,
        ItemIconType.BOOK to R.drawable.ic_item_book,
        ItemIconType.BOOMERANG to R.drawable.ic_item_boomerang,
        ItemIconType.BOTTLE to R.drawable.ic_item_bottle,
        ItemIconType.BUGNET to R.drawable.ic_item_bugnet,
        ItemIconType.CARAPACEON_SHELL to R.drawable.ic_item_carapaceon_shell,
        ItemIconType.COIN to R.drawable.ic_item_coin,
        ItemIconType.DUNG to R.drawable.ic_item_dung,
        ItemIconType.EGG to R.drawable.ic_item_egg,
        ItemIconType.EMPTY_BOTTLE to R.drawable.ic_item_empty_bottle,
        ItemIconType.FANG to R.drawable.ic_item_fang,
        ItemIconType.FISH to R.drawable.ic_item_fish,
        ItemIconType.FLUTE to R.drawable.ic_item_flute,
        ItemIconType.HERB to R.drawable.ic_item_herb,
        ItemIconType.HONEY to R.drawable.ic_item_honey,
        ItemIconType.HUSK to R.drawable.ic_item_husk,
        ItemIconType.HEAVENLY_SCALE to R.drawable.ic_item_heavenly_scale,
        ItemIconType.INSECT to R.drawable.ic_item_insect,
        ItemIconType.JEWEL to R.drawable.ic_item_jewel,
        ItemIconType.KNIFE to R.drawable.ic_item_knife,
        ItemIconType.LIQUID to R.drawable.ic_item_liquid,
        ItemIconType.MAP to R.drawable.ic_item_map,
        ItemIconType.MEAT to R.drawable.ic_item_meat,
        ItemIconType.MONSTER to R.drawable.ic_item_monster,
        ItemIconType.MUSHROOM to R.drawable.ic_item_mushroom,
        ItemIconType.ORE to R.drawable.ic_item_ore,
        ItemIconType.PELT to R.drawable.ic_item_pelt,
        ItemIconType.PICKAXE to R.drawable.ic_item_pickaxe,
        ItemIconType.SCALE to R.drawable.ic_item_scale,
        ItemIconType.SEED to R.drawable.ic_item_seed,
        ItemIconType.SHELL to R.drawable.ic_item_shell,
        ItemIconType.SMOKE to R.drawable.ic_item_smoke,
        ItemIconType.TICKET to R.drawable.ic_item_ticket,
        ItemIconType.TOOL to R.drawable.ic_item_tool,
        ItemIconType.TRAP to R.drawable.ic_item_trap,
        ItemIconType.UNKNOWN to R.drawable.ic_item_unknown,
        ItemIconType.WEB to R.drawable.ic_item_web,
        ItemIconType.WHETSTONE to R.drawable.ic_item_whetstone
    )

    val locations: Map<Int, Int> = mapOf(
        1 to R.drawable.ic_location_snowy_mountains,
        2 to R.drawable.ic_location_jungle,
        3 to R.drawable.ic_location_old_jungle,
        4 to R.drawable.ic_location_desert,
        5 to R.drawable.ic_location_old_desert,
        6 to R.drawable.ic_location_swamp,
        7 to R.drawable.ic_location_old_swamp,
        8 to R.drawable.ic_location_volcano,
        9 to R.drawable.ic_location_old_volcano,
        10 to R.drawable.ic_location_forest_and_hills,
        11 to R.drawable.ic_location_great_forest,
        12 to R.drawable.ic_location_tower_1,
        13 to R.drawable.ic_location_tower_2,
        14 to R.drawable.ic_location_tower_3,
        15 to R.drawable.ic_location_fortress,
        16 to R.drawable.ic_location_town,
        17 to R.drawable.ic_location_castle_schrade,
        18 to R.drawable.ic_location_battleground,
        19 to R.drawable.ic_location_snowy_mountains_peak,
        20 to R.drawable.ic_location_arena,
        21 to R.drawable.ic_location_moat_arena,
        22 to R.drawable.ic_location_great_arena,
    )

    val monsters: Map<Int, Int> = mapOf(
        1 to R.drawable.ic_monster_felyne,
        2 to R.drawable.ic_monster_melynx,
        3 to R.drawable.ic_monster_shakalaka,
        4 to R.drawable.ic_monster_king_shakalaka,
        5 to R.drawable.ic_monster_vespoid,
        6 to R.drawable.ic_monster_vespoid_queen,
        7 to R.drawable.ic_monster_hornetaur,
        8 to R.drawable.ic_monster_great_thunderbug,
        9 to R.drawable.ic_monster_anteka,
        10 to R.drawable.ic_monster_popo,
        11 to R.drawable.ic_monster_kelbi,
        12 to R.drawable.ic_monster_mosswine,
        13 to R.drawable.ic_monster_aptonoth,
        14 to R.drawable.ic_monster_apceros,
        15 to R.drawable.ic_monster_giaprey,
        16 to R.drawable.ic_monster_giadrome,
        17 to R.drawable.ic_monster_velociprey,
        18 to R.drawable.ic_monster_velocidrome,
        19 to R.drawable.ic_monster_genprey,
        20 to R.drawable.ic_monster_gendrome,
        21 to R.drawable.ic_monster_ioprey,
        22 to R.drawable.ic_monster_iodrome,
        23 to R.drawable.ic_monster_yian_kut_ku,
        24 to R.drawable.ic_monster_blue_yian_kut_ku,
        25 to R.drawable.ic_monster_yian_garuga,
        26 to R.drawable.ic_monster_scarred_yian_garuga,
        27 to R.drawable.ic_monster_gypceros,
        28 to R.drawable.ic_monster_purple_gypceros,
        29 to R.drawable.ic_monster_hypnocatrice,
        30 to R.drawable.ic_monster_remobra,
        31 to R.drawable.ic_monster_rathian,
        32 to R.drawable.ic_monster_pink_rathian,
        33 to R.drawable.ic_monster_gold_rathian,
        34 to R.drawable.ic_monster_rathalos,
        35 to R.drawable.ic_monster_azure_rathalos,
        36 to R.drawable.ic_monster_silver_rathalos,
        37 to R.drawable.ic_monster_khezu,
        38 to R.drawable.ic_monster_red_khezu,
        39 to R.drawable.ic_monster_basarios,
        40 to R.drawable.ic_monster_gravios,
        41 to R.drawable.ic_monster_black_gravios,
        42 to R.drawable.ic_monster_monoblos,
        43 to R.drawable.ic_monster_white_monoblos,
        44 to R.drawable.ic_monster_diablos,
        45 to R.drawable.ic_monster_black_diablos,
        46 to R.drawable.ic_monster_tigrex,
        47 to R.drawable.ic_monster_nargacuga,
        48 to R.drawable.ic_monster_akantor,
        49 to R.drawable.ic_monster_ukanlos,
        50 to R.drawable.ic_monster_cephalos,
        51 to R.drawable.ic_monster_cephadrome,
        52 to R.drawable.ic_monster_plesioth,
        53 to R.drawable.ic_monster_green_plesioth,
        54 to R.drawable.ic_monster_lavasioth,
        55 to R.drawable.ic_monster_hermitaur,
        56 to R.drawable.ic_monster_daimyo_hermitaur,
        57 to R.drawable.ic_monster_plum_daimyo_hermitaur,
        58 to R.drawable.ic_monster_ceanataur,
        59 to R.drawable.ic_monster_shogun_ceanataur,
        60 to R.drawable.ic_monster_terra_shogun_ceanataur,
        61 to R.drawable.ic_monster_shen_gaoren,
        62 to R.drawable.ic_monster_bullfango,
        63 to R.drawable.ic_monster_bulldrome,
        64 to R.drawable.ic_monster_conga,
        65 to R.drawable.ic_monster_congalala,
        66 to R.drawable.ic_monster_esmerald_congalala,
        67 to R.drawable.ic_monster_blango,
        68 to R.drawable.ic_monster_blangonga,
        69 to R.drawable.ic_monster_copper_blangonga,
        70 to R.drawable.ic_monster_rajang,
        71 to R.drawable.ic_monster_furious_rajang,
        72 to R.drawable.ic_monster_kirin,
        73 to R.drawable.ic_monster_kushala_daora,
        74 to R.drawable.ic_monster_rusted_kushala_daora,
        75 to R.drawable.ic_monster_chameleos,
        76 to R.drawable.ic_monster_lunastra,
        77 to R.drawable.ic_monster_teostra,
        78 to R.drawable.ic_monster_lao_shan_lung,
        79 to R.drawable.ic_monster_ashen_lao_shan_lung,
        80 to R.drawable.ic_monster_yama_tsukami,
        81 to R.drawable.ic_monster_fatalis,
        82 to R.drawable.ic_monster_crimson_fatalis,
        83 to R.drawable.ic_monster_white_fatalis,
    )

    val weapons: Map<WeaponType, Int> = mapOf(
        WeaponType.GREAT_SWORD to R.drawable.ic_weapon_great_sword,
        WeaponType.LONG_SWORD to R.drawable.ic_weapon_long_sword,
        WeaponType.SWORD_AND_SHIELD to R.drawable.ic_weapon_sword_and_shield,
        WeaponType.DUAL_BLADES to R.drawable.ic_weapon_dual_blades,
        WeaponType.HAMMER to R.drawable.ic_weapon_hammer,
        WeaponType.HUNTING_HORN to R.drawable.ic_weapon_hunting_horn,
        WeaponType.LANCE to R.drawable.ic_weapon_lance,
        WeaponType.GUNLANCE to R.drawable.ic_weapon_gunlance,
        WeaponType.LIGHT_BOWGUN to R.drawable.ic_weapon_light_bowgun,
        WeaponType.HEAVY_BOWGUN to R.drawable.ic_weapon_heavy_bowgun,
        WeaponType.BOW to R.drawable.ic_weapon_bow
    )

}
