import '../domain/enums.dart';
import '../../l10n/app_localizations.dart';

String questGroupLabel(AppLocalizations l10n, QuestGroup group) =>
    switch (group) {
      QuestGroup.village1 => l10n.questGroupVillage1,
      QuestGroup.village2 => l10n.questGroupVillage2,
      QuestGroup.village3 => l10n.questGroupVillage3,
      QuestGroup.village4 => l10n.questGroupVillage4,
      QuestGroup.village5 => l10n.questGroupVillage5,
      QuestGroup.village6 => l10n.questGroupVillage6,
      QuestGroup.village7 => l10n.questGroupVillage7,
      QuestGroup.village8 => l10n.questGroupVillage8,
      QuestGroup.village9 => l10n.questGroupVillage9,
      QuestGroup.hr1a => l10n.questGroupHr1a,
      QuestGroup.hr1b => l10n.questGroupHr1b,
      QuestGroup.hr1c => l10n.questGroupHr1c,
      QuestGroup.hr2 => l10n.questGroupHr2,
      QuestGroup.hr3 => l10n.questGroupHr3,
      QuestGroup.hr4 => l10n.questGroupHr4,
      QuestGroup.hr5 => l10n.questGroupHr5,
      QuestGroup.hr6 => l10n.questGroupHr6,
      QuestGroup.hr7 => l10n.questGroupHr7,
      QuestGroup.hr8 => l10n.questGroupHr8,
      QuestGroup.hr9 => l10n.questGroupHr9,
      QuestGroup.treasure => l10n.questGroupTreasure,
      QuestGroup.event => l10n.questGroupEvent,
      QuestGroup.beginnerBasic => l10n.questGroupBeginnerBasic,
      QuestGroup.beginnerWeapon => l10n.questGroupBeginnerWeapon,
      QuestGroup.trainingBattle => l10n.questGroupTrainingBattle,
      QuestGroup.trainingSpecial => l10n.questGroupTrainingSpecial,
      QuestGroup.trainingG => l10n.questGroupTrainingG,
      QuestGroup.groupPractice => l10n.questGroupGroupPractice,
      QuestGroup.groupChallenge => l10n.questGroupGroupChallenge,
    };

String questGroupSummaryLabel(AppLocalizations l10n, QuestGroup group) =>
    switch (group) {
      QuestGroup.village1 => l10n.questGroupSummaryVillage1,
      QuestGroup.village2 => l10n.questGroupSummaryVillage2,
      QuestGroup.village3 => l10n.questGroupSummaryVillage3,
      QuestGroup.village4 => l10n.questGroupSummaryVillage4,
      QuestGroup.village5 => l10n.questGroupSummaryVillage5,
      QuestGroup.village6 => l10n.questGroupSummaryVillage6,
      QuestGroup.village7 => l10n.questGroupSummaryVillage7,
      QuestGroup.village8 => l10n.questGroupSummaryVillage8,
      QuestGroup.village9 => l10n.questGroupSummaryVillage9,
      QuestGroup.hr1a => l10n.questGroupSummaryHr1a,
      QuestGroup.hr1b => l10n.questGroupSummaryHr1b,
      QuestGroup.hr1c => l10n.questGroupSummaryHr1c,
      QuestGroup.hr2 => l10n.questGroupSummaryHr2,
      QuestGroup.hr3 => l10n.questGroupSummaryHr3,
      QuestGroup.hr4 => l10n.questGroupSummaryHr4,
      QuestGroup.hr5 => l10n.questGroupSummaryHr5,
      QuestGroup.hr6 => l10n.questGroupSummaryHr6,
      QuestGroup.hr7 => l10n.questGroupSummaryHr7,
      QuestGroup.hr8 => l10n.questGroupSummaryHr8,
      QuestGroup.hr9 => l10n.questGroupSummaryHr9,
      QuestGroup.treasure => l10n.questGroupSummaryTreasure,
      QuestGroup.event => l10n.questGroupSummaryEvent,
      QuestGroup.beginnerBasic => l10n.questGroupSummaryBeginnerBasic,
      QuestGroup.beginnerWeapon => l10n.questGroupSummaryBeginnerWeapon,
      QuestGroup.trainingBattle => l10n.questGroupSummaryTrainingBattle,
      QuestGroup.trainingSpecial => l10n.questGroupSummaryTrainingSpecial,
      QuestGroup.trainingG => l10n.questGroupSummaryTrainingG,
      QuestGroup.groupPractice => l10n.questGroupSummaryGroupPractice,
      QuestGroup.groupChallenge => l10n.questGroupSummaryGroupChallenge,
    };

String questGroupDetailLabel(AppLocalizations l10n, QuestGroup group) =>
    switch (group) {
      QuestGroup.village1 => l10n.questGroupDetailVillage1,
      QuestGroup.village2 => l10n.questGroupDetailVillage2,
      QuestGroup.village3 => l10n.questGroupDetailVillage3,
      QuestGroup.village4 => l10n.questGroupDetailVillage4,
      QuestGroup.village5 => l10n.questGroupDetailVillage5,
      QuestGroup.village6 => l10n.questGroupDetailVillage6,
      QuestGroup.village7 => l10n.questGroupDetailVillage7,
      QuestGroup.village8 => l10n.questGroupDetailVillage8,
      QuestGroup.village9 => l10n.questGroupDetailVillage9,
      QuestGroup.hr1a => l10n.questGroupDetailHr1a,
      QuestGroup.hr1b => l10n.questGroupDetailHr1b,
      QuestGroup.hr1c => l10n.questGroupDetailHr1c,
      QuestGroup.hr2 => l10n.questGroupDetailHr2,
      QuestGroup.hr3 => l10n.questGroupDetailHr3,
      QuestGroup.hr4 => l10n.questGroupDetailHr4,
      QuestGroup.hr5 => l10n.questGroupDetailHr5,
      QuestGroup.hr6 => l10n.questGroupDetailHr6,
      QuestGroup.hr7 => l10n.questGroupDetailHr7,
      QuestGroup.hr8 => l10n.questGroupDetailHr8,
      QuestGroup.hr9 => l10n.questGroupDetailHr9,
      QuestGroup.treasure => l10n.questGroupDetailTreasure,
      QuestGroup.event => l10n.questGroupDetailEvent,
      QuestGroup.beginnerBasic => l10n.questGroupDetailBeginnerBasic,
      QuestGroup.beginnerWeapon => l10n.questGroupDetailBeginnerWeapon,
      QuestGroup.trainingBattle => l10n.questGroupDetailTrainingBattle,
      QuestGroup.trainingSpecial => l10n.questGroupDetailTrainingSpecial,
      QuestGroup.trainingG => l10n.questGroupDetailTrainingG,
      QuestGroup.groupPractice => l10n.questGroupDetailGroupPractice,
      QuestGroup.groupChallenge => l10n.questGroupDetailGroupChallenge,
    };
