import 'package:flutter/material.dart';

import 'app_colors.dart';

final lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: primaryLight,
  onPrimary: onPrimaryLight,
  primaryContainer: primaryContainerLight,
  onPrimaryContainer: onPrimaryContainerLight,
  secondary: secondaryLight,
  onSecondary: onSecondaryLight,
  secondaryContainer: secondaryContainerLight,
  onSecondaryContainer: onSecondaryContainerLight,
  tertiary: tertiaryLight,
  onTertiary: onTertiaryLight,
  tertiaryContainer: tertiaryContainerLight,
  onTertiaryContainer: onTertiaryContainerLight,
  error: errorLight,
  onError: onErrorLight,
  errorContainer: errorContainerLight,
  onErrorContainer: onErrorContainerLight,
  surface: surfaceLight,
  onSurface: onSurfaceLight,
  surfaceContainerHighest: surfaceContainerHighestLight,
  onSurfaceVariant: onSurfaceVariantLight,
  outline: outlineLight,
  outlineVariant: outlineVariantLight,
  shadow: scrimLight,
  scrim: scrimLight,
  inverseSurface: inverseSurfaceLight,
  onInverseSurface: inverseOnSurfaceLight,
  inversePrimary: inversePrimaryLight,
  surfaceDim: surfaceDimLight,
  surfaceBright: surfaceBrightLight,
  surfaceContainerLowest: surfaceContainerLowestLight,
  surfaceContainerLow: surfaceContainerLowLight,
  surfaceContainer: surfaceContainerLight,
  surfaceContainerHigh: surfaceContainerHighLight,
);

final darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: primaryDark,
  onPrimary: onPrimaryDark,
  primaryContainer: primaryContainerDark,
  onPrimaryContainer: onPrimaryContainerDark,
  secondary: secondaryDark,
  onSecondary: onSecondaryDark,
  secondaryContainer: secondaryContainerDark,
  onSecondaryContainer: onSecondaryContainerDark,
  tertiary: tertiaryDark,
  onTertiary: onTertiaryDark,
  tertiaryContainer: tertiaryContainerDark,
  onTertiaryContainer: onTertiaryContainerDark,
  error: errorDark,
  onError: onErrorDark,
  errorContainer: errorContainerDark,
  onErrorContainer: onErrorContainerDark,
  surface: surfaceDark,
  onSurface: onSurfaceDark,
  surfaceContainerHighest: surfaceContainerHighestDark,
  onSurfaceVariant: onSurfaceVariantDark,
  outline: outlineDark,
  outlineVariant: outlineVariantDark,
  shadow: scrimDark,
  scrim: scrimDark,
  inverseSurface: inverseSurfaceDark,
  onInverseSurface: inverseOnSurfaceDark,
  inversePrimary: inversePrimaryDark,
  surfaceDim: surfaceDimDark,
  surfaceBright: surfaceBrightDark,
  surfaceContainerLowest: surfaceContainerLowestDark,
  surfaceContainerLow: surfaceContainerLowDark,
  surfaceContainer: surfaceContainerDark,
  surfaceContainerHigh: surfaceContainerHighDark,
);

ThemeData buildAppTheme(ColorScheme colorScheme) {
  return ThemeData(
    useMaterial3: true,
    colorScheme: colorScheme,
    scaffoldBackgroundColor: colorScheme.brightness == Brightness.light
        ? backgroundLight
        : backgroundDark,
    appBarTheme: const AppBarTheme(
      backgroundColor: Colors.transparent,
      surfaceTintColor: Colors.transparent,
      elevation: 0,
      scrolledUnderElevation: 0,
      actionsPadding: EdgeInsetsDirectional.only(end: 4),
    ),
  );
}
